language: python
dist: xenial

python:
    - "2.7"
    - "3.6"
    - "3.7"

matrix:
  include:
    - os: linux
      python: 3.7
      install: python setup.py -q install
      script:
      - flake8
      - mypy . --ignore-missing-imports
      after_success:
      - pytest tests
    - os: osx
      language: sh
      install: pip3 install -e .

install:
  - python setup.py -q install
# command to run tests
script: pytest tests
