language: python
dist: xenial
env: #

python:
- '2.7'
- '3.6'
- '3.7'
matrix:
  include:
  - os: linux
    python: 3.7
    env: ALLOW_FAILURE=true
    install:
    - python setup.py -q install
    - pip install flake8
    - pip install mypy
    script:
    - flake8
    after_success:
    - pytest tests
  - os: osx
    language: sh
    install:
    - pip3 install -e .
    - pip install pytest
  allow_failures:
  - env: ALLOW_FAILURE=true
  - os: osx
  fast_finish: true
install:
- python setup.py -q install
script: pytest tests
notifications:
  slack:
    secure: RniqcaY/p0otq2vDQxcg07hSjrBK8Wz4xB8RWC86lrc+g9BFZfkmATfkQhBiUB/Pk0ntIk0BAuMP8P8wjz9nfsYyd6PgLF0bi41NVuzuQYPp7GJ0LWAPfptAoBDDb1xOQb4VFyIBhL0BWZVNycDG3rtL0j7gSJJNG1KOdU/lHqs3R9yTwAvMtYj8wNAt0E2teCI95fdDYsv/0CYqBKjMWyxRLASmujIfcofWOttIyMTfKQISUrN5yhxbHeNwSUsk2mK6fy9IY0DYDuiIKW3C49zkPAqJAl1+nwVsabn7il8UO8NEQqEIBnLro2mao0aoqWWlANs5EhZ1xvzKmEWjVH5nQxXnvnK2YUR+Ko5NTC4O/anaO9hiusrVjUdv7zty2OObybHrUL0zNVngLONec2XrON4BpJo1DTT+ZMJ00WOd4edOtqVWZrZIkQpPlNwF4Pcgr5yAX7MG2I5mUa5JtwJsxVXehecjhIp6aIoYoxZqwZIT8eu0/xJpHjcruVQwb49Jd1kktMujR/xHfI9YCU9eMP23Ib1oUd9ppelHh6edtFryk9J0d1m/ALJ/QllwidQFiFJglspaYZIUcY/EIWJ7GzXjPerLD/c9Bl2FqJqAEAxfoY7051ibU8P6SOt9j+vqqha6yCnuehZhHDrSCyhHEN7AIAJYIZ09Enhz2ko=
    on_success: change # default: always
    on_failure: change # default: always
  email: false
