language: python
dist: xenial

python:
    - "2.7"
    - "3.6"
    - "3.7"

matrix:
  include:
    - os: linux
      python: 3.7
      install: 
      - python setup.py -q install
      - pip install flake8
      - pip install mypy
      script:
      - flake8
      - mypy . --ignore-missing-imports
      after_success:
      - pytest tests
    - os: osx
      language: sh
      install: 
      - pip3 install -e .
      - pip install pytest
  allow_failures:
    - python: 3.7
      script: flake8
  fast_finish: true

install:
  - python setup.py -q install
# command to run tests
script: pytest tests
